mod DATA-STREAM-CASES is
  pr TEE-BEHAVIOR .
  pr TEE-IMP-BEHAVIOR .
  pr MQTTZ-PROGRAM-DECL .
  pr MQTTZ-DATA .
  pr MQTTZ-CONSTANTS .
  pr MQTTZ-RA-BEHAVIOR .

  op testDataStream : -> Program [ctor] .

  op openedHandleToPersistentObj : -> Stmt [ctor] .
  eq openedHandleToPersistentObj = 
      OpenPersistentObject(# TEE-STORAGE-PRIVATE, # fileName(pub(1)), 
                           # (TEE-DATA-FLAG-ACCESS-READ, TEE-DATA-FLAG-SHARE-READ,
                              TEE-DATA-FLAG-ACCESS-WRITE, TEE-DATA-FLAG-SHARE-WRITE) ; res, object) .

  eq testDataStream = 
    main () {
      var res ; var object ;
      var data ;

      --- Location: read_raw_object
      --- Test Case 1 (For TEE_ReadObjectData)
      --- openedHandleToPersistentObj ;
      --- ReadObjectData(object, # dataSize(1)  ; res, data) ;
      --- return data

      --- Test Case 2 (TEE_WriteObjectData)
      openedHandleToPersistentObj ;
      WriteObjectData(object, # attrContentData(keyAttrValue(pub(2)))  ; res ) ;
      return res
    }
  .
endm