load ../main
load test-transient
load test-persistent

mod TEST-CASES is
  pr TEST-TRANSIENT .
  pr TEST-PERSISTENT .
endm

mod TEST-SCENARIO is
  pr SCENARIO-AUX .
  pr TEST-CASES .

  vars P TAPROG : Program .

  op initTestTa : Program -> Configuration .
  eq initTestTa(P) = < ta : TrustApp | proc : none , prog : P , running : false ,
                                       app-status : normal , api-call : noCall , api-return : noReturn ,
                                       current-api : noApi , api-state : noState , current-params : empty , id-counter : 0 ,
                                       trust-app-id : GATEKEEPER ,
                                       task : task({sessionId(0) , main , nil} , ra) , task-counter : 0 , state-changed : false > .

  op scenario : Program -> Configuration .
  eq scenario(TAPROG) 
   = initTestTa(TAPROG) initTrustedOS masterKey .

endm

--- rew scenario(testTransientTA) .
rew scenario(testPersistentTA) .