mod TEST-PERSISTENT is
  pr TEE-BEHAVIOR .
  pr TEE-IMP-BEHAVIOR .
  pr GATEKEEPER-PROGRAM-DECL .
  pr GATEKEEPER-DATA .

  op testPersistentTA : -> Program [ctor] .

  eq testPersistentTA = 
    main () {
      --- Location: TA_GetMasterKey
      var res ; var	secretObj ;
    	secretObj := # TEE-HANDLE-NULL ;
      OpenPersistentObject(# TEE-STORAGE-PRIVATE, # secretID, # TEE-DATA-FLAG-ACCESS-READ  ; res , secretObj) ;
      return res
    }
  .
endm