mod TEST-DATA-STREAM is
  pr TEE-BEHAVIOR .
  pr TEE-IMP-BEHAVIOR .
  pr GATEKEEPER-PROGRAM-DECL .
  pr GATEKEEPER-DATA .

  op testDataStreamTA : -> Program [ctor] .

  eq testDataStreamTA = 
    main () {
      --- Location: TA_CreatePasswordHandle
      var res ; var	secretObj ;
    	secretObj := # TEE-HANDLE-NULL ;
      OpenPersistentObject(# TEE-STORAGE-PRIVATE, # secretID, # TEE-DATA-FLAG-ACCESS-READ  ; res , secretObj) ;

      var secretData ;      
      ReadObjectData(secretObj, # dataSize(1)  ; res, secretData) ;
      return secretData
    }
  .
endm